---
- name: check entropy available
  command: cat /proc/sys/kernel/random/entropy_avail
  register: entropy_avail
  changed_when: no

- name: install haveged if needed
  include: install_haveged.yml
  when: entropy_avail|int < min_entropy
